name: CI Validate

on:
  push:
    branches: [ main ]
    paths:
      - 'ceremony/**'
      - 'repository/**'
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748 # v2.4.0
        with:
          fetch-depth: 0
      - run: |
          echo "REPO=$(pwd)/repository" >> $GITHUB_ENV
          echo "GCS_REPO=https://storage.googleapis.com/sigstore-tuf-root" >> $GITHUB_ENV
      - uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab # v2.2.0
        with:
          go-version: '1.16.4'
      - name: install deps
        run: |
          sudo apt-get install libpcsclite-dev
          curl -fsO https://developers.yubico.com/PIV/Introduction/piv-attestation-ca.pem
      - name: build
        run: go build -o verify ./cmd/verify/
      - name: build
        run: go build -o tuf -tags=pivkey ./cmd/tuf
      - name: verify local published repository
        run: ./verify repository --repository $REPO --root $(pwd)/ceremony/2021-06-18/repository/root.json
      - name: verify GCS remote published repository
        run: ./verify repository --repository $GCS_REPO --root $(pwd)/ceremony/2021-06-18/repository/root.json

